# DevSpace configuration for n8n with ARK custom nodes
version: v2beta1

images:
  ark-n8n:
    image: ark-n8n
    dockerfile: Dockerfile
    context: .
    buildKit: {}
    docker:
      preferMinikube: false

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all
  dev: |-
    build_images --all
    create_deployments --all
    start_dev --all

deployments:
  ark-n8n:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: ${runtime.images.ark-n8n.image}
            tag: ${runtime.images.ark-n8n.tag}
            pullPolicy: Never
          # Override resources for local development
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          # Override environment for dev mode via HTTPRoute
          env:
            N8N_HOST: ark-n8n-devspace.default.127.0.0.1.nip.io
            N8N_EDITOR_BASE_URL: http://ark-n8n-devspace.default.127.0.0.1.nip.io
            N8N_PUSH_BACKEND: websocket
        httpRoute:
          enabled: true
          hostnames:
            - ark-n8n-devspace.default.127.0.0.1.nip.io
          origin: http://ark-n8n-devspace.default.127.0.0.1.nip.io

dev:
  ark-n8n:
    imageSelector: ark-n8n
    namespace: default
    logs:
      lastLines: 50
    ports:
      - port: "5678:80"
    sync:
      - path: /tmp/n8n-devspace:/home/node/.n8n
        printLogs: true
        initialSync: preferRemote
