{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-route
  labels:
    app: {{ .Values.app.name }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gateway.name }}
    namespace: {{ .Values.httpRoute.gateway.namespace }}
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- $root := . }}
  {{- range .Values.httpRoute.rules }}
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: Origin
          value: {{ $root.Values.httpRoute.origin | default (printf "%s://%s" ($root.Values.app.env.N8N_PROTOCOL | default "http") (index $root.Values.httpRoute.hostnames 0)) | quote }}
        - name: X-Forwarded-Proto
          value: {{ $root.Values.app.env.N8N_PROTOCOL | default "http" | quote }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name }}
      port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}
