---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-nginx-proxy-config
  namespace: default
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 8080;
        server_name _;

        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        location / {
          # Forward to n8n service
          proxy_pass http://ark-n8n:5678;

          # Critical: Set Origin header that n8n expects
          # Use the actual host header from the request
          proxy_set_header Origin http://$host;

          # Standard proxy headers
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $http_host;

          # WebSocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # Timeouts for long-running requests
          proxy_connect_timeout 3600s;
          proxy_send_timeout 3600s;
          proxy_read_timeout 3600s;

          # Disable buffering for streaming responses
          proxy_buffering off;
          proxy_request_buffering off;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-nginx-proxy
  namespace: default
  labels:
    app: n8n-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-nginx-proxy
  template:
    metadata:
      labels:
        app: n8n-nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: n8n-nginx-proxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-nginx-proxy
  namespace: default
  labels:
    app: n8n-nginx-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: n8n-nginx-proxy
