name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: nodes/package-lock.json

      - name: Install dependencies
        run: |
          cd nodes
          npm ci

      - name: Run tests with coverage
        run: |
          cd nodes
          npm run test:coverage

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: nodes/coverage/

      - name: Check coverage threshold
        if: success()
        run: |
          cd nodes
          if [ ! -f coverage/coverage-summary.json ]; then
            echo "Error: coverage-summary.json not found"
            exit 1
          fi
          COVERAGE=$(node -pe "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json')).total.lines.pct")
          echo "Coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Coverage below 80% threshold"
            exit 1
          fi
