name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: nodes/package-lock.json

      - name: Install dependencies
        run: |
          cd nodes
          npm ci

      - name: Run tests with coverage
        run: |
          cd nodes
          npm run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: nodes/coverage/

      - name: Check coverage threshold
        run: |
          cd nodes
          COVERAGE=$(grep -oP '(?<=All files\s+\|\s+)\d+\.\d+' coverage/coverage-summary.json | head -n 1 || echo "0")
          echo "Coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Coverage below 80% threshold"
            exit 1
          fi
